// Renders the Inputs block of the docs/tools/<tool>.md pages from the JSON Schema the server registers.
// Dev-only: it lives outside src/, so it is neither built nor shipped. Run it with `npm run docs:tools`.
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { format, resolveConfig } from "prettier";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import type { Tool } from "@modelcontextprotocol/sdk/types.js";
import { createServer } from "../../src/server.js";

export const INPUTS_START = "<!-- generated:inputs start -->";
export const INPUTS_END = "<!-- generated:inputs end -->";

const GENERATED_COMMENT = "<!-- Generated by npm run docs:tools from the registered input schema. Do not edit. -->";

const TOP_LEVEL_KEYWORDS = new Set(["$schema", "type", "properties", "required", "additionalProperties"]);
const PROPERTY_KEYWORDS = new Set([
  "type",
  "description",
  "enum",
  "default",
  "minimum",
  "maximum",
  "exclusiveMinimum",
  "exclusiveMaximum",
  "minLength",
  "maxLength",
  "pattern",
  "items",
  "minItems",
  "maxItems",
]);
const ITEMS_KEYWORDS = new Set(["type", "enum", "minimum", "maximum", "exclusiveMinimum", "exclusiveMaximum"]);
const SCALAR_TYPES = new Set(["integer", "string", "boolean", "number"]);
const NUMBER_TYPES = new Set(["integer", "number"]);
// Keywords that apply to some types only: JSON Schema ignores them on the others, so rendering them there misleads
const TYPE_KEYWORDS: Record<string, Set<string>> = {
  minimum: NUMBER_TYPES,
  maximum: NUMBER_TYPES,
  exclusiveMinimum: NUMBER_TYPES,
  exclusiveMaximum: NUMBER_TYPES,
  minLength: new Set(["string"]),
  maxLength: new Set(["string"]),
  pattern: new Set(["string"]),
  items: new Set(["array"]),
  minItems: new Set(["array"]),
  maxItems: new Set(["array"]),
};

type Schema = Record<string, unknown>;

/** Lists the tools exactly as an MCP client sees them, from the same createServer() the stdio entry point runs. */
export async function listRegisteredTools(): Promise<Tool[]> {
  const server = createServer();
  const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
  const client = new Client({ name: "docs-tools", version: "0.0.0" });
  await Promise.all([server.connect(serverTransport), client.connect(clientTransport)]);
  try {
    return (await client.listTools()).tools;
  } finally {
    await client.close();
    await server.close();
  }
}

function checkKeywords(schema: Schema, allowed: Set<string>, where: string): void {
  for (const keyword of Object.keys(schema)) {
    if (!allowed.has(keyword)) throw new Error(`Unsupported JSON Schema keyword "${keyword}" in ${where}`);
  }
}

function checkTypeKeywords(schema: Schema, type: string, where: string): void {
  for (const keyword of Object.keys(schema)) {
    if (TYPE_KEYWORDS[keyword]?.has(type) === false) {
      throw new Error(`Unsupported JSON Schema keyword "${keyword}" on type ${type} in ${where}`);
    }
  }
}

function numberOf(schema: Schema, keyword: string, where: string): number | undefined {
  const value = schema[keyword];
  if (value === undefined) return undefined;
  if (typeof value !== "number") throw new Error(`Unsupported JSON Schema value for "${keyword}" in ${where}`);
  return value;
}

function stringOf(schema: Schema, keyword: string, where: string): string | undefined {
  const value = schema[keyword];
  if (value === undefined) return undefined;
  if (typeof value !== "string") throw new Error(`Unsupported JSON Schema value for "${keyword}" in ${where}`);
  return value;
}

function valuesOf(schema: Schema, where: string): unknown[] | undefined {
  const value = schema.enum;
  if (value === undefined) return undefined;
  if (!Array.isArray(value)) throw new Error(`Unsupported JSON Schema value for "enum" in ${where}`);
  return value as unknown[];
}

function asSchema(value: unknown, where: string): Schema {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new Error(`Unsupported JSON Schema in ${where}`);
  }
  return value as Schema;
}

/** An inline code span that survives backticks in its content. */
function code(text: string): string {
  const longestRun = Math.max(0, ...(text.match(/`+/g) ?? []).map((run) => run.length));
  const fence = "`".repeat(longestRun + 1);
  const pad = text.startsWith("`") || text.endsWith("`") ? " " : "";
  return `${fence}${pad}${text}${pad}${fence}`;
}

/** Escapes the characters Markdown would read as markup; an underscore inside a word stays as is. */
function escapeMarkdown(text: string): string {
  return text
    .replace(/[\\`*[\]<>|~]/g, "\\$&")
    .replace(/_/g, (underscore, offset: number) =>
      /\w/.test(text.charAt(offset - 1)) && /\w/.test(text.charAt(offset + 1)) ? underscore : "\\_",
    );
}

function escapeCell(text: string): string {
  return text.replace(/\|/g, "\\|");
}

function count(n: number, unit: string): string {
  return `${n} ${unit}${n === 1 ? "" : "s"}`;
}

function typeOf(schema: Schema, where: string): string {
  const type = schema.type;
  if (type === "array") {
    const items = asSchema(schema.items, `${where}.items`);
    checkKeywords(items, ITEMS_KEYWORDS, `${where}.items`);
    if (typeof items.type !== "string" || !SCALAR_TYPES.has(items.type)) {
      throw new Error(`Unsupported JSON Schema type in ${where}.items`);
    }
    checkTypeKeywords(schema, type, where);
    checkTypeKeywords(items, items.type, `${where}.items`);
    return `array of ${items.type}`;
  }
  if (typeof type !== "string" || !SCALAR_TYPES.has(type)) throw new Error(`Unsupported JSON Schema type in ${where}`);
  checkTypeKeywords(schema, type, where);
  return type;
}

/** The numeric bounds of a value: "1 to 50", "≥ 0", "≤ 4810", "> 0", "< 1". */
function boundsOf(schema: Schema, where: string): string[] {
  const constraints: string[] = [];
  const minimum = numberOf(schema, "minimum", where);
  const rawMaximum = numberOf(schema, "maximum", where);
  // documentId() bounds IDs with an explicit .max(Number.MAX_SAFE_INTEGER) (src/tools/inputs.ts), which says nothing
  // to a reader
  const maximum = rawMaximum === Number.MAX_SAFE_INTEGER ? undefined : rawMaximum;
  const exclusiveMinimum = numberOf(schema, "exclusiveMinimum", where);
  const exclusiveMaximum = numberOf(schema, "exclusiveMaximum", where);
  if (minimum !== undefined && maximum !== undefined) {
    constraints.push(`${minimum} to ${maximum}`);
  } else if (minimum !== undefined) {
    constraints.push(`≥ ${minimum}`);
  } else if (maximum !== undefined) {
    constraints.push(`≤ ${maximum}`);
  }
  if (exclusiveMinimum !== undefined) constraints.push(`> ${exclusiveMinimum}`);
  if (exclusiveMaximum !== undefined) constraints.push(`< ${exclusiveMaximum}`);
  return constraints;
}

function constraintsOf(schema: Schema, where: string): string[] {
  const constraints = boundsOf(schema, where);
  const minLength = numberOf(schema, "minLength", where);
  const maxLength = numberOf(schema, "maxLength", where);
  if (minLength !== undefined) constraints.push(`at least ${count(minLength, "character")}`);
  if (maxLength !== undefined) constraints.push(`at most ${count(maxLength, "character")}`);
  const pattern = stringOf(schema, "pattern", where);
  if (pattern !== undefined) constraints.push(`pattern ${code(pattern)}`);

  const minItems = numberOf(schema, "minItems", where);
  const maxItems = numberOf(schema, "maxItems", where);
  if (minItems !== undefined) constraints.push(`at least ${count(minItems, "item")}`);
  if (maxItems !== undefined) constraints.push(`at most ${count(maxItems, "item")}`);
  if (schema.type === "array") {
    const items = `${where}.items`;
    constraints.push(...boundsOf(asSchema(schema.items, items), items).map((bound) => `each ${bound}`));
  }
  return constraints;
}

function bulletOf(name: string, schema: Schema, where: string): string {
  const parts: string[] = [];
  // A line break would end the bullet, so the lines of a multi-line description are joined with a space
  const description = stringOf(schema, "description", where)
    ?.trim()
    .replace(/\s*[\r\n]\s*/g, " ");
  if (description) parts.push(escapeMarkdown(/[.!?]$/.test(description) ? description : `${description}.`));
  const values = valuesOf(schema, where) ?? valuesOf(asSchema(schema.items ?? {}, `${where}.items`), `${where}.items`);
  if (values !== undefined) parts.push(`Values: ${values.map((value) => code(String(value))).join(", ")}`);
  return `- ${code(name)}${parts.length > 0 ? `: ${parts.join(" ")}` : ""}`;
}

/**
 * Renders the Inputs block of a tool: the generated comment, one table row and one bullet per parameter,
 * in registration order. Throws on any JSON Schema keyword it does not know how to document.
 */
export function renderInputs(tool: Tool): string {
  const inputSchema: Schema = tool.inputSchema;
  checkKeywords(inputSchema, TOP_LEVEL_KEYWORDS, tool.name);
  const required = new Set(tool.inputSchema.required ?? []);
  const rows: string[] = [];
  const bullets: string[] = [];
  for (const [name, value] of Object.entries(tool.inputSchema.properties ?? {})) {
    const where = `${tool.name}.${name}`;
    const schema = asSchema(value, where);
    checkKeywords(schema, PROPERTY_KEYWORDS, where);
    const cells = [
      code(name),
      typeOf(schema, where),
      required.has(name) ? "yes" : "no",
      schema.default === undefined ? "" : code(JSON.stringify(schema.default)),
      constraintsOf(schema, where).join(", "),
    ];
    rows.push(`|${cells.map((cell) => (cell ? ` ${escapeCell(cell)} |` : " |")).join("")}`);
    bullets.push(bulletOf(name, schema, where));
  }
  return [
    GENERATED_COMMENT,
    "",
    "| Parameter | Type | Required | Default | Constraints |",
    "| --- | --- | --- | --- | --- |",
    ...rows,
    "",
    ...bullets,
    "",
  ].join("\n");
}

function markerIndex(page: string, marker: string, file: string): number {
  const index = page.indexOf(marker);
  if (index === -1) throw new Error(`${file}: missing marker ${marker}`);
  if (page.includes(marker, index + marker.length)) throw new Error(`${file}: duplicated marker ${marker}`);
  return index;
}

/** Replaces the text between the markers with `block`; everything outside the markers is kept byte for byte. */
export function replaceInputsBlock(page: string, block: string, file: string): string {
  const start = markerIndex(page, INPUTS_START, file);
  const end = markerIndex(page, INPUTS_END, file);
  if (end < start) throw new Error(`${file}: marker ${INPUTS_END} comes before ${INPUTS_START}`);
  return `${page.slice(0, start + INPUTS_START.length)}\n\n${block.trim()}\n\n${page.slice(end)}`;
}

/** The skeleton of a page for a tool that has none yet; the sections other than Inputs are written by hand. */
export function newToolPage(tool: Tool): string {
  return [
    `# ${tool.name}`,
    "",
    "## Purpose",
    "",
    escapeMarkdown(tool.description ?? ""),
    "",
    "## Inputs",
    "",
    INPUTS_START,
    INPUTS_END,
    "",
    "## Related tools",
    "",
  ].join("\n");
}

/** Formats Markdown with the Prettier configuration that applies to `file`, as `npm run format:check` does. */
export async function formatMarkdown(text: string, file: string): Promise<string> {
  const config = await resolveConfig(file);
  return format(text, { ...config, parser: "markdown" });
}

export async function renderToolPage(tool: Tool, current: string, file: string): Promise<string> {
  return formatMarkdown(replaceInputsBlock(current, renderInputs(tool), file), file);
}

export type PageStatus = "created" | "updated" | "unchanged";

async function readIfExists(file: string): Promise<string | undefined> {
  try {
    return await readFile(file, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw error;
  }
}

/** Renders `<dir>/<tool>.md` for every tool, creating missing pages. Renders them all before writing any. */
export async function writeToolPages(tools: Tool[], dir: string): Promise<{ file: string; status: PageStatus }[]> {
  const pages: { file: string; current: string | undefined; next: string }[] = [];
  for (const tool of tools) {
    const file = join(dir, `${tool.name}.md`);
    const current = await readIfExists(file);
    pages.push({ file, current, next: await renderToolPage(tool, current ?? newToolPage(tool), file) });
  }
  await mkdir(dir, { recursive: true });
  const results: { file: string; status: PageStatus }[] = [];
  for (const { file, current, next } of pages) {
    if (current === next) {
      results.push({ file, status: "unchanged" });
    } else {
      await writeFile(file, next);
      results.push({ file, status: current === undefined ? "created" : "updated" });
    }
  }
  return results;
}
