import { afterEach, describe, it, expect } from "vitest";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import type { Tool } from "@modelcontextprotocol/sdk/types.js";
import {
  INPUTS_END,
  INPUTS_START,
  listRegisteredTools,
  newToolPage,
  renderInputs,
  renderToolPage,
  replaceInputsBlock,
  writeToolPages,
} from "../../scripts/docs/inputs.js";

// A file inside this checkout, so that resolveConfig() finds the repo's .prettierrc.json
const PAGE_FILE = fileURLToPath(new URL("../../docs/tools/search_fixture.md", import.meta.url));

// Mirrors the JSON Schema the server registers for search_outings / search_routes (see the registration snapshot)
function fixtureTool(): Tool {
  return {
    name: "search_fixture",
    description: "Search fixtures",
    inputSchema: {
      $schema: "http://json-schema.org/draft-07/schema#",
      type: "object",
      properties: {
        query: { type: "string", maxLength: 200, description: "Keyword (e.g. 'cosmiques')" },
        area_id: {
          type: "integer",
          exclusiveMinimum: 0,
          maximum: Number.MAX_SAFE_INTEGER,
          description: "Camptocamp area ID from search_areas",
        },
        date_from: { type: "string", pattern: "^\\d{4}-\\d{2}-\\d{2}$", description: "Earliest date (YYYY-MM-DD)." },
        route_types: {
          type: "array",
          items: { type: "string", enum: ["return_same_way", "loop"] },
          minItems: 1,
          description: "Route types, matching any of: return_same_way, loop",
        },
        limit: { type: "integer", minimum: 1, maximum: 50, default: 10, description: "Maximum number of results" },
        offset: { type: "integer", minimum: 0, default: 0, description: "Number of results to skip" },
      },
      required: ["query"],
      additionalProperties: false,
    },
  };
}

function withProperty(name: string, schema: Record<string, unknown>): Tool {
  const tool = fixtureTool();
  return { ...tool, inputSchema: { ...tool.inputSchema, properties: { [name]: schema } } };
}

function row(block: string, name: string): string {
  const line = block.split("\n").find((l) => l.startsWith(`| \`${name}\` |`));
  if (line === undefined) throw new Error(`no row for ${name} in:\n${block}`);
  return line;
}

describe("renderInputs", () => {
  const block = renderInputs(fixtureTool());

  it("starts with the generated comment and the table header", () => {
    expect(block.split("\n").slice(0, 4)).toEqual([
      "<!-- Generated by npm run docs:tools from the registered input schema. Do not edit. -->",
      "",
      "| Parameter | Type | Required | Default | Constraints |",
      "| --- | --- | --- | --- | --- |",
    ]);
  });

  it("lists the parameters in registration order", () => {
    const names = block
      .split("\n")
      .filter((l) => l.startsWith("| `"))
      .map((l) => /^\| `(\w+)`/.exec(l)?.[1]);
    expect(names).toEqual(["query", "area_id", "date_from", "route_types", "limit", "offset"]);
  });

  it("renders an ID field as a positive integer, without the safe-integer maximum", () => {
    expect(row(block, "area_id")).toBe("| `area_id` | integer | no | | > 0 |");
    expect(block).not.toContain(String(Number.MAX_SAFE_INTEGER));
  });

  it("renders the limit default and its range", () => {
    expect(row(block, "limit")).toBe("| `limit` | integer | no | `10` | 1 to 50 |");
    expect(row(block, "offset")).toBe("| `offset` | integer | no | `0` | ≥ 0 |");
  });

  it("renders an array type, its item count and its values", () => {
    expect(row(block, "route_types")).toBe("| `route_types` | array of string | no | | at least 1 item |");
    expect(block).toContain(
      "- `route_types`: Route types, matching any of: return_same_way, loop. Values: `return_same_way`, `loop`",
    );
  });

  it("renders a pattern", () => {
    expect(row(block, "date_from")).toBe("| `date_from` | string | no | | pattern `^\\d{4}-\\d{2}-\\d{2}$` |");
  });

  it("shows a required field as yes, with its length limit", () => {
    expect(row(block, "query")).toBe("| `query` | string | yes | | at most 200 characters |");
  });

  it("writes one bullet per parameter, ending the description with a single period", () => {
    expect(block).toContain("- `query`: Keyword (e.g. 'cosmiques').\n");
    expect(block).toContain("- `date_from`: Earliest date (YYYY-MM-DD).\n");
    expect(block).not.toContain("..");
  });

  it("renders the remaining bounds and string defaults", () => {
    const tool = fixtureTool();
    const rendered = renderInputs({
      ...tool,
      inputSchema: {
        ...tool.inputSchema,
        required: undefined,
        properties: {
          lang: { type: "string", enum: ["fr", "en"], default: "fr" },
          ratio: { type: "number", exclusiveMinimum: 0, exclusiveMaximum: 1 },
          altitude: { type: "integer", maximum: 4810 },
          code: { type: "string", minLength: 1, maxLength: 1, pattern: "a|`b`" },
          tags: { type: "array", items: { type: "string" }, minItems: 2, maxItems: 1 },
          flag: { type: "boolean" },
        },
      },
    });
    expect(row(rendered, "lang")).toBe('| `lang` | string | no | `"fr"` | |');
    expect(rendered).toContain("- `lang`: Values: `fr`, `en`\n");
    expect(rendered).toContain("- `flag`\n");
    expect(row(rendered, "ratio")).toBe("| `ratio` | number | no | | > 0, < 1 |");
    expect(row(rendered, "altitude")).toBe("| `altitude` | integer | no | | ≤ 4810 |");
    expect(row(rendered, "code")).toBe(
      "| `code` | string | no | | at least 1 character, at most 1 character, pattern `` a\\|`b` `` |",
    );
    expect(row(rendered, "tags")).toBe("| `tags` | array of string | no | | at least 2 items, at most 1 item |");
  });

  it("escapes Markdown punctuation in descriptions", () => {
    const rendered = renderInputs(withProperty("q", { type: "string", description: "a*b <c> [d] e|f `g` _h_ ~i~ \\" }));
    expect(rendered).toContain("- `q`: a\\*b \\<c\\> \\[d\\] e\\|f \\`g\\` \\_h\\_ \\~i\\~ \\\\.");
  });

  it("throws on an unknown keyword, naming the tool and the field", () => {
    expect(() => renderInputs(withProperty("when", { anyOf: [{ type: "string" }, { type: "integer" }] }))).toThrow(
      'Unsupported JSON Schema keyword "anyOf" in search_fixture.when',
    );
    expect(() =>
      renderInputs(withProperty("tags", { type: "array", items: { type: "string", minLength: 1 } })),
    ).toThrow('Unsupported JSON Schema keyword "minLength" in search_fixture.tags.items');
    const tool = fixtureTool();
    expect(() => renderInputs({ ...tool, inputSchema: { ...tool.inputSchema, definitions: {} } })).toThrow(
      'Unsupported JSON Schema keyword "definitions" in search_fixture',
    );
  });

  it("throws on a type it cannot render", () => {
    expect(() => renderInputs(withProperty("x", { type: ["string", "null"] }))).toThrow(
      "Unsupported JSON Schema type in search_fixture.x",
    );
    expect(() => renderInputs(withProperty("x", { type: "array" }))).toThrow(
      "Unsupported JSON Schema in search_fixture.x.items",
    );
    expect(() => renderInputs(withProperty("x", { type: "integer", minimum: "1" }))).toThrow(
      'Unsupported JSON Schema value for "minimum" in search_fixture.x',
    );
  });
});

describe("replaceInputsBlock", () => {
  const page = `# t\n\n## Inputs\n\nbefore ${INPUTS_START}\nold\n${INPUTS_END} after\n\n## Related tools\n`;

  it("replaces only the text between the markers", () => {
    expect(replaceInputsBlock(page, "new\n", "t.md")).toBe(
      `# t\n\n## Inputs\n\nbefore ${INPUTS_START}\n\nnew\n\n${INPUTS_END} after\n\n## Related tools\n`,
    );
  });

  it("throws on missing, duplicated or out-of-order markers, naming the file", () => {
    expect(() => replaceInputsBlock("# t\n", "x", "t.md")).toThrow(`t.md: missing marker ${INPUTS_START}`);
    expect(() => replaceInputsBlock(`${INPUTS_START}\n`, "x", "t.md")).toThrow(`t.md: missing marker ${INPUTS_END}`);
    expect(() => replaceInputsBlock(`${page}${INPUTS_START}\n`, "x", "t.md")).toThrow(
      `t.md: duplicated marker ${INPUTS_START}`,
    );
    expect(() => replaceInputsBlock(`${page}${INPUTS_END}\n`, "x", "t.md")).toThrow(
      `t.md: duplicated marker ${INPUTS_END}`,
    );
    expect(() => replaceInputsBlock(`${INPUTS_END}\n${INPUTS_START}\n`, "x", "t.md")).toThrow(
      `t.md: marker ${INPUTS_END} comes before ${INPUTS_START}`,
    );
  });
});

describe("tool pages", () => {
  it("creates a page with the sections and both markers", () => {
    const page = newToolPage(fixtureTool());
    expect(page).toMatch(/^# search_fixture\n/);
    expect(page.indexOf("## Purpose")).toBeLessThan(page.indexOf("## Inputs"));
    expect(page.indexOf("## Inputs")).toBeLessThan(page.indexOf(INPUTS_START));
    expect(page.indexOf(INPUTS_START)).toBeLessThan(page.indexOf(INPUTS_END));
    expect(page.indexOf(INPUTS_END)).toBeLessThan(page.indexOf("## Related tools"));
  });

  it("renders a formatted page, and rendering it again changes nothing", async () => {
    const tool = fixtureTool();
    const once = await renderToolPage(tool, newToolPage(tool), PAGE_FILE);
    expect(once).toMatch(/\n\| `area_id` +\| integer +\| no +\| +\| > 0 +\|\n/);
    expect(await renderToolPage(tool, once, PAGE_FILE)).toBe(once);
  });
});

describe("registered tools", () => {
  it("renders the schema of all 13 registered tools", async () => {
    const tools = await listRegisteredTools();
    expect(tools).toHaveLength(13);
    for (const tool of tools) {
      expect(renderInputs(tool)).toContain(`| \`lang\` | string | no |`);
    }
  });
});

describe("writeToolPages", () => {
  let dir: string | undefined;

  afterEach(async () => {
    if (dir !== undefined) await rm(dir, { recursive: true, force: true });
  });

  it("creates missing pages, updates stale ones and leaves current ones alone", async () => {
    dir = await mkdtemp(join(tmpdir(), "docs-tools-"));
    const pagesDir = join(dir, "docs", "tools");
    const tool = fixtureTool();
    const other: Tool = { ...tool, name: "get_fixture" };

    expect(await writeToolPages([tool], pagesDir)).toEqual([
      { file: join(pagesDir, "search_fixture.md"), status: "created" },
    ]);
    const created = await readFile(join(pagesDir, "search_fixture.md"), "utf8");
    await writeFile(
      join(pagesDir, "get_fixture.md"),
      `# get_fixture\n\nKept.\n\n${INPUTS_START}\nstale\n${INPUTS_END}\n`,
    );

    expect(await writeToolPages([tool, other], pagesDir)).toEqual([
      { file: join(pagesDir, "search_fixture.md"), status: "unchanged" },
      { file: join(pagesDir, "get_fixture.md"), status: "updated" },
    ]);
    expect(await readFile(join(pagesDir, "search_fixture.md"), "utf8")).toBe(created);
    const updated = await readFile(join(pagesDir, "get_fixture.md"), "utf8");
    expect(updated).toMatch(/^# get_fixture\n\nKept\.\n/);
    expect(updated).not.toContain("stale");
  });

  it("writes nothing when a page cannot be rendered", async () => {
    dir = await mkdtemp(join(tmpdir(), "docs-tools-"));
    const broken: Tool = { ...withProperty("when", { anyOf: [] }), name: "get_fixture" };
    await expect(writeToolPages([fixtureTool(), broken], dir)).rejects.toThrow('"anyOf"');
    await expect(readFile(join(dir, "search_fixture.md"), "utf8")).rejects.toThrow("ENOENT");
  });
});
